namespace EFOOD___FRONTEND___DESKTOP.Models.Menu_Module.routers
{
    /*AS ROTAS SÃO RESPONSÁVEIS PARA INDICAR O CAMINHO NO QUAL DEVE SER ENVIADA A REQUISIÇÃO HTTP PARA OBTER RETORNO
   DA API NODEJS, TODOS OS MÉTODOS NA API, TEM UMA ROTA NO QUAL DEVE SER CHAMADA PELO FRONT END QUE ESTÁ CONSUMINDO*/
    public class menu_principal_admins_router_routers
    {
    }
}