namespace EFOOD___FRONTEND___DESKTOP.Models.Home_Module.routers
{
    /*AS ROTAS SÃO RESPONSÁVEIS PARA INDICAR O CAMINHO NO QUAL DEVE SER ENVIADA A REQUISIÇÃO HTTP PARA OBTER RETORNO
   DA API NODEJS, TODOS OS MÉTODOS NA API, TEM UMA ROTA NO QUAL DEVE SER CHAMADA PELO FRONT END QUE ESTÁ CONSUMINDO*/
    public class home_router_routers
    {
    }
}